[tasks.'test:coverage']
condition = { platforms = ["linux", "mac"] }
script = [
    "rm -rf ./coverage",
    "mkdir -p ./coverage",
    "cargo llvm-cov",
    "cargo llvm-cov --lcov --output-path ./coverage/lcov.info >/dev/null 2>&1",
]

[tasks.'test:coverage-win']
condition = { platforms = ["windows"] }
script = [
    "if exist ./coverage rmdir /s /q ./coverage",
    "mkdir ./coverage",
    "cargo llvm-cov",
    "cargo llvm-cov --lcov --output-path ./coverage/lcov.info >nul 2>&1",
]
